import { post } from "../models/post";

export const posts:post[] = [
    {
        id : 1,
        post_date: "July 31, 2021",
        semi_heading: "Capgemini Off Campus Drive",
        heading: "Capgemini Off Campus Drive 2021 for SAP | B.E/B.Tech | 2019/2020 Batch | Across India",
        description: "Capgemini scheduled to hire for the role of SAP – SD  and SAP – MM for B.E/ B.Tech graduates – 2019/ 2020 batch. The detailed eligibility and application process are given below.",
        img_url: "https://www.autonewspress.com/wp-content/uploads/2020/09/capgemini-logo.jpg",
        job_role: "SAP – SD",
        qualification:	"B.E/B.Tech",
        batch: "2019/2020",
        experience: "1 – 2 years",
        salary:	"Rs. 3 – 3.8 LPA",
        job_location: "Bangalore/Chennai/Mumbai/Pune",
        drive_location: null,
        drive_date: null,
        last_date: "ASAP",
        detailed_eligibility: [
            "B.E/ B.Tech (Any Specialization)",
            "Minimum Marks 60% Graduation in 2019 & 2020",
            "Min. Class XII Marks: 50%", 
            "Min. Class X Marks: 50%",
            "No Backlogs Accepted"
        ],
        professional_experience: [
            "Domain experience of minimum 1 – 2 years in any of the following areas",
            "Sale coordinators (back office customer service)",
            "Warehouse or store keepers dealing with a different type of goods movement.",
            "Manufacturing experience including raw material to finished product processing.",
            "The business role involved sales order, delivery, shipment & billing document processing.",
            "Basic Business process understating is required"
        ],
        skills: [
            "Good communication skills – both oral & written – in English",
            "Right attitude & temperament",
            "Quick grasping power",
            "Excellent written and oral communication skills",
            "Team Player",
            "Interacting with People",
            "Flexibility in terms of technology adaption.",
        ],
        job_description:null,
        apply_link: "https://www.firstnaukri.com/job-listings-SAP-SD-Engg-jobs-in-Bengaluru-Bangalore-Chennai-Mumbai-Pune-in-Capgemini-Technology-Services-India-Limited-280721600016?srchId=&srchRank=1&pageNo=1",

    },
    {
        id : 2,
        post_date: "July 31, 2021",
        semi_heading: "Accenture Off Campus Event 2021",
        heading: "Accenture Off Campus Drive 2021 | B.E/B.Tech/M.E/M.Tech/MCA/M.Sc/B.Sc/BCA | 2019/2020/2021 Batch | Across India",
        description: "Accenture Solutions Pvt Ltd planned to conduct Off Campus Drive to hire B.E/B.Tech/M.E/M.Tech/MCA/M.Sc & B.Sc/BCA 2019,2020,2021 Batch graduates. The more details about Accenture off campus drive given below.",
        img_url: "https://media-exp1.licdn.com/dms/image/C4E0BAQHjvfNL_2AXIw/company-logo_200_200/0/1628018657141?e=2159024400&v=beta&t=cmvXa6kojPE5fkxVXbL_VOWgXQvNbRBrjy0oWNh3pyo",
        job_role: "Associate Software Engineer",
        qualification:	"B.E/B.Tech/M.E/M.Tech/MCA/M.Sc",
        batch: "2019/2020/2021",
        experience: "0-1 Year",
        salary:	"Rs 4.5 LPA",
        job_location: "Bangalore, Hyderabad, Chennai, Mumbai, Pune, Gurugram",
        drive_location:"Online(Virtual)",
        drive_date:"Announced Later",
        last_date: "10 August 2021",
        detailed_eligibility: [
            "Full time program in B.E. / B. Tech / M.E / M.Tech / MCA / M.Sc (All streams).",
            "Year of passing: Graduates from 2019/2020/2021.",
            "Backlogs: No active backlogs both during application and at the time of Onboarding.",
            "Gap in Education: Maximum 1-year gap in education (post 10th standard till completion of graduation).",
            "Applied for Accenture Candidate should not have appeared for Accenture Recruitment assessment / interview process in last three months",
            "Work Permit: Should be an Indian Citizen. Bhutan & Nepal nationals can work in India without a need for obtaining a visa to work. All other foreign nationals require work visa or an OCI / PIO card to work in India. Bhutan & Nepal nationals would also need to submit a Citizenship certificate or a Govt. ID Card in the absence of other documents (PIO/OCI/Work permit/passport)"
        ],
        professional_experience: [
            "Domain experience of minimum 1 – 2 years in any of the following areas",
            "Sale coordinators (back office customer service)",
            "Warehouse or store keepers dealing with a different type of goods movement.",
            "Manufacturing experience including raw material to finished product processing.",
            "The business role involved sales order, delivery, shipment & billing document processing.",
            "Basic Business process understating is required"
        ],
        skills: [
            "Good communication skills – both oral & written – in English",
            "Right attitude & temperament",
            "Quick grasping power",
            "Excellent written and oral communication skills",
            "Team Player",
            "Interacting with People",
            "Flexibility in terms of technology adaption.",
        ],
        job_description:[
            "Design, build, test, assemble, support, and configure the application using business requirements",
            "Understand business drivers that will impact performance and deliver software to those expectations",
            "Bake technology trends into solutions; Participate in the development of automation solutions, new functionality, and technologies and integrate them into existing solutions",
            "Responsible for incident resolution and support extended to customers through voice interaction/email/chat/remote support"
        ],
        apply_link: "https://indiacampus.accenture.com/register/accenture/ndirl1/apply/?event=3233",

    },
    {
        id : 3,
        post_date: "August 3, 2021",
        semi_heading: "Accolite Digital Off Campus Drive 2021",
        heading: "Accolite Digital Off Campus Drive 2021 for Software Engineers | B.E/B.Tech/MCA | Last Date: 6 August 2021",
        description: "scheduled for Freshers for B.E/B.Tech/MCA- 2021 batch graduates. The detailed eligibility and application process are given below",
        img_url: "https://media-exp1.licdn.com/dms/image/C560BAQHtwUTC4975SQ/company-logo_200_200/0/1627901210445?e=2159024400&v=beta&t=ryX4fB1NZ0kkeQzSQ7uMyg80CBtIXlSCBxJQ0Amf4DU",
        job_role: "Software Engineer",
        qualification:	"B.E/B.Tech/MCA",
        batch: "2021",
        experience: "Freshers",
        salary:	"Best in Industry",
        job_location: "Bangalore",
        drive_location:"Gurgaon/Hyderabad/Bangalore",
        drive_date: null,
        last_date: "6 August 2021",
        detailed_eligibility: [
            "B.Tech/ B.E/ MCA (Only 2021 batch)",
            "10th/12th or Diploma/UG/PG minimum 60% or 6 CGPA.",
            "No Gaps in Education.",
            "Full-time, UGC-recognized education in 10th, 12th, diploma, graduation and post graduation.",
            "Distance Learning or part-time or part-time degrees will not be considered.",
        ],
        professional_experience: null,
        skills: [
            "Familiar with the software development life cycle (SDLC) from analysis to deployment.",
            "Comply with coding standards and technical design.",
            "Believes in systematic approach to developing the system through clear documentation (flowcharts, layouts, & etc) of functionality, address every use case through creative solutions."
        ],
        job_description:[
            "you will be the brain behind crafting, developing, testing, going live and maintaining the system. You are passionate in understanding the business context for features built to drive better customer experience and adoption"
        ],
        apply_link: "https://docs.google.com/forms/d/e/1FAIpQLSfFD16nWU7crGRfDwSpclNtfiLTlVn736ceaB3pEq8AjoXHPg/viewform",

    },
    {
        id : 4,
        post_date: "August 1, 2021",
        semi_heading: "Subex Off Campus Drive 2021",
        heading: "Subex Off Campus Drive 2021 for Software Engineers | B.E/B.Tech | 2021 Batch | Bangalore",
        description: "Subex Off Campus Drive 2021 scheduled for Freshers for B.E/B.Tech- 2021 batch graduates. The detailed eligibility and application process are given below.",
        img_url: "https://media-exp1.licdn.com/dms/image/C4D0BAQFKe7i5lOfjJA/company-logo_200_200/0/1625117872450?e=2159024400&v=beta&t=kKkiiY53SKQ-xv3FJaFZy5gZ0ohYvYwKcOwU1dZ--tc",
        job_role: "Software Engineer",
        qualification:	"B.E/B.Tech",
        batch: "2021",
        experience: "Freshers",
        salary:	"Rs 5 LPA",
        job_location: "Bangalore",
        drive_location:"Virtual",
        drive_date: null,
        last_date: "ASAP",
        detailed_eligibility: [
            "B.E./B. Tech – CSE/IT/ISE with 65% and above throughout.",
            "No Standing Arrears.",
            "Very Good Communication skill",
            "Strong technical knowledge on the programming language (Java, Data Structures, Algorithms, Sql)",
            "Knowledge on BIG Data Hadoop, Analytics, AI, ML, IOT security",
            "Articulation of thoughts and converting them into good writing skills",
            "Good logical and aptitude solving skill"
        ],
        professional_experience: null,
        skills: null,
        job_description: null,
        apply_link: "https://docs.google.com/forms/d/e/1FAIpQLSdOIVKsvKX1lTNFUtet0F8v6sv9DZ_4iqf9Z_-UXrEFxyYLgw/viewform",

    },
    {
        id : 5,
        post_date: "August 1, 2021",
        semi_heading: "ITC Infotech Off-Campus Drive 2021",
        heading: "ITC Infotech Off Campus Referral Drive 2021 | B.E/B.Tech | Across India",
        description: "ITC Infotech is hiring fresh engineering graduates who are looking to start their career in Automation, Data, ADM, Testing, IT Infra, Product 4.0 offerings.. The detailed eligibility criteria and application process are given below.",
        img_url: "https://media-exp1.licdn.com/dms/image/C4D0BAQHChIp3T3c83w/company-logo_200_200/0/1519855878132?e=2159024400&v=beta&t=B3YArJ-sqhF1OCsmTp8qnZ6Jw9Pu9xdbC8WTNDWygXk",
        job_role: "Graduate Engineer Trainee",
        qualification:	"B.E/B.Tech",
        batch: "2021",
        experience: "0 – 1 Year",
        salary:	"Best in Industry",
        job_location: "Bangalore, Coimbatore, Kolkata, Pune, & Guwahati",
        drive_location: null,
        drive_date: null,
        last_date: "ASAP",
        detailed_eligibility: [
            "B.E/B.Tech freshers (CSE,ECE,EEE & IT) with 60% throughout in 10, 12th and Graduation with no active backlog",
            "Year of passing: 2021",
            "Candidates should be open to get posted at any of the above location"
        ],
        professional_experience: null,
        skills: null,
        job_description: null,
        apply_link: "https://jobs.itcinfotech.com/referral/#/job-list",

    },
    
]