import { post } from "../models/post";

export const posts:post[] = [
    {
        id : 1,
        post_date: "July 31, 2021",
        semi_heading: "Capgemini Off Campus Drive",
        heading: "Capgemini Off Campus Drive 2021 for SAP | B.E/B.Tech | 2019/2020 Batch | Across India",
        description: "Capgemini scheduled to hire for the role of SAP – SD  and SAP – MM for B.E/ B.Tech graduates – 2019/ 2020 batch. The detailed eligibility and application process are given below.",
        img_url: "https://www.autonewspress.com/wp-content/uploads/2020/09/capgemini-logo.jpg",
        job_role: "SAP – SD",
        qualification:	"B.E/B.Tech",
        batch: "2019/2020",
        experience: "1 – 2 years",
        salary:	"Rs. 3 – 3.8 LPA",
        job_location: "Bangalore/Chennai/Mumbai/Pune",
        drive_location: null,
        drive_date: null,
        last_date: "ASAP",
        detailed_eligibility: [
            "B.E/ B.Tech (Any Specialization)",
            "Minimum Marks 60% Graduation in 2019 & 2020",
            "Min. Class XII Marks: 50%", 
            "Min. Class X Marks: 50%",
            "No Backlogs Accepted"
        ],
        professional_experience: [
            "Domain experience of minimum 1 – 2 years in any of the following areas",
            "Sale coordinators (back office customer service)",
            "Warehouse or store keepers dealing with a different type of goods movement.",
            "Manufacturing experience including raw material to finished product processing.",
            "The business role involved sales order, delivery, shipment & billing document processing.",
            "Basic Business process understating is required"
        ],
        skills: [
            "Good communication skills – both oral & written – in English",
            "Right attitude & temperament",
            "Quick grasping power",
            "Excellent written and oral communication skills",
            "Team Player",
            "Interacting with People",
            "Flexibility in terms of technology adaption.",
        ],
        job_description:null,
        apply_link: "https://www.firstnaukri.com/job-listings-SAP-SD-Engg-jobs-in-Bengaluru-Bangalore-Chennai-Mumbai-Pune-in-Capgemini-Technology-Services-India-Limited-280721600016?srchId=&srchRank=1&pageNo=1",

    },
    {
        id : 2,
        post_date: "July 31, 2021",
        semi_heading: "Accenture Off Campus Event 2021",
        heading: "Accenture Off Campus Drive 2021 | B.E/B.Tech/M.E/M.Tech/MCA/M.Sc/B.Sc/BCA | 2019/2020/2021 Batch | Across India",
        description: "Accenture Solutions Pvt Ltd planned to conduct Off Campus Drive to hire B.E/B.Tech/M.E/M.Tech/MCA/M.Sc & B.Sc/BCA 2019,2020,2021 Batch graduates. The more details about Accenture off campus drive given below.",
        img_url: "https://media-exp1.licdn.com/dms/image/C4E0BAQHjvfNL_2AXIw/company-logo_200_200/0/1628018657141?e=2159024400&v=beta&t=cmvXa6kojPE5fkxVXbL_VOWgXQvNbRBrjy0oWNh3pyo",
        job_role: "Associate Software Engineer",
        qualification:	"B.E/B.Tech/M.E/M.Tech/MCA/M.Sc",
        batch: "2019/2020/2021",
        experience: "0-1 Year",
        salary:	"Rs 4.5 LPA",
        job_location: "Bangalore, Hyderabad, Chennai, Mumbai, Pune, Gurugram",
        drive_location:"Online(Virtual)",
        drive_date:"Announced Later",
        last_date: "10 August 2021",
        detailed_eligibility: [
            "Full time program in B.E. / B. Tech / M.E / M.Tech / MCA / M.Sc (All streams).",
            "Year of passing: Graduates from 2019/2020/2021.",
            "Backlogs: No active backlogs both during application and at the time of Onboarding.",
            "Gap in Education: Maximum 1-year gap in education (post 10th standard till completion of graduation).",
            "Applied for Accenture Candidate should not have appeared for Accenture Recruitment assessment / interview process in last three months",
            "Work Permit: Should be an Indian Citizen. Bhutan & Nepal nationals can work in India without a need for obtaining a visa to work. All other foreign nationals require work visa or an OCI / PIO card to work in India. Bhutan & Nepal nationals would also need to submit a Citizenship certificate or a Govt. ID Card in the absence of other documents (PIO/OCI/Work permit/passport)"
        ],
        professional_experience: [
            "Domain experience of minimum 1 – 2 years in any of the following areas",
            "Sale coordinators (back office customer service)",
            "Warehouse or store keepers dealing with a different type of goods movement.",
            "Manufacturing experience including raw material to finished product processing.",
            "The business role involved sales order, delivery, shipment & billing document processing.",
            "Basic Business process understating is required"
        ],
        skills: [
            "Good communication skills – both oral & written – in English",
            "Right attitude & temperament",
            "Quick grasping power",
            "Excellent written and oral communication skills",
            "Team Player",
            "Interacting with People",
            "Flexibility in terms of technology adaption.",
        ],
        job_description:[
            "Design, build, test, assemble, support, and configure the application using business requirements",
            "Understand business drivers that will impact performance and deliver software to those expectations",
            "Bake technology trends into solutions; Participate in the development of automation solutions, new functionality, and technologies and integrate them into existing solutions",
            "Responsible for incident resolution and support extended to customers through voice interaction/email/chat/remote support"
        ],
        apply_link: "https://indiacampus.accenture.com/register/accenture/ndirl1/apply/?event=3233",

    },
    {
        id : 3,
        post_date: "August 3, 2021",
        semi_heading: "Accolite Digital Off Campus Drive 2021",
        heading: "Accolite Digital Off Campus Drive 2021 for Software Engineers | B.E/B.Tech/MCA | Last Date: 6 August 2021",
        description: "scheduled for Freshers for B.E/B.Tech/MCA- 2021 batch graduates. The detailed eligibility and application process are given below",
        img_url: "https://media-exp1.licdn.com/dms/image/C560BAQHtwUTC4975SQ/company-logo_200_200/0/1627901210445?e=2159024400&v=beta&t=ryX4fB1NZ0kkeQzSQ7uMyg80CBtIXlSCBxJQ0Amf4DU",
        job_role: "Software Engineer",
        qualification:	"B.E/B.Tech/MCA",
        batch: "2021",
        experience: "Freshers",
        salary:	"Best in Industry",
        job_location: "Bangalore",
        drive_location:"Gurgaon/Hyderabad/Bangalore",
        drive_date: null,
        last_date: "6 August 2021",
        detailed_eligibility: [
            "B.Tech/ B.E/ MCA (Only 2021 batch)",
            "10th/12th or Diploma/UG/PG minimum 60% or 6 CGPA.",
            "No Gaps in Education.",
            "Full-time, UGC-recognized education in 10th, 12th, diploma, graduation and post graduation.",
            "Distance Learning or part-time or part-time degrees will not be considered.",
        ],
        professional_experience: null,
        skills: [
            "Familiar with the software development life cycle (SDLC) from analysis to deployment.",
            "Comply with coding standards and technical design.",
            "Believes in systematic approach to developing the system through clear documentation (flowcharts, layouts, & etc) of functionality, address every use case through creative solutions."
        ],
        job_description:[
            "you will be the brain behind crafting, developing, testing, going live and maintaining the system. You are passionate in understanding the business context for features built to drive better customer experience and adoption"
        ],
        apply_link: "https://docs.google.com/forms/d/e/1FAIpQLSfFD16nWU7crGRfDwSpclNtfiLTlVn736ceaB3pEq8AjoXHPg/viewform",

    },
    {
        id : 4,
        post_date: "August 1, 2021",
        semi_heading: "Subex Off Campus Drive 2021",
        heading: "Subex Off Campus Drive 2021 for Software Engineers | B.E/B.Tech | 2021 Batch | Bangalore",
        description: "Subex Off Campus Drive 2021 scheduled for Freshers for B.E/B.Tech- 2021 batch graduates. The detailed eligibility and application process are given below.",
        img_url: "https://media-exp1.licdn.com/dms/image/C4D0BAQFKe7i5lOfjJA/company-logo_200_200/0/1625117872450?e=2159024400&v=beta&t=kKkiiY53SKQ-xv3FJaFZy5gZ0ohYvYwKcOwU1dZ--tc",
        job_role: "Software Engineer",
        qualification:	"B.E/B.Tech",
        batch: "2021",
        experience: "Freshers",
        salary:	"Rs 5 LPA",
        job_location: "Bangalore",
        drive_location:"Virtual",
        drive_date: null,
        last_date: "ASAP",
        detailed_eligibility: [
            "B.E./B. Tech – CSE/IT/ISE with 65% and above throughout.",
            "No Standing Arrears.",
            "Very Good Communication skill",
            "Strong technical knowledge on the programming language (Java, Data Structures, Algorithms, Sql)",
            "Knowledge on BIG Data Hadoop, Analytics, AI, ML, IOT security",
            "Articulation of thoughts and converting them into good writing skills",
            "Good logical and aptitude solving skill"
        ],
        professional_experience: null,
        skills: null,
        job_description: null,
        apply_link: "https://docs.google.com/forms/d/e/1FAIpQLSdOIVKsvKX1lTNFUtet0F8v6sv9DZ_4iqf9Z_-UXrEFxyYLgw/viewform",

    },
    {
        id : 5,
        post_date: "August 1, 2021",
        semi_heading: "ITC Infotech Off-Campus Drive 2021",
        heading: "ITC Infotech Off Campus Referral Drive 2021 | B.E/B.Tech | Across India",
        description: "ITC Infotech is hiring fresh engineering graduates who are looking to start their career in Automation, Data, ADM, Testing, IT Infra, Product 4.0 offerings.. The detailed eligibility criteria and application process are given below.",
        img_url: "https://media-exp1.licdn.com/dms/image/C4D0BAQHChIp3T3c83w/company-logo_200_200/0/1519855878132?e=2159024400&v=beta&t=B3YArJ-sqhF1OCsmTp8qnZ6Jw9Pu9xdbC8WTNDWygXk",
        job_role: "Graduate Engineer Trainee",
        qualification:	"B.E/B.Tech",
        batch: "2021",
        experience: "0 – 1 Year",
        salary:	"Best in Industry",
        job_location: "Bangalore, Coimbatore, Kolkata, Pune, & Guwahati",
        drive_location: null,
        drive_date: null,
        last_date: "ASAP",
        detailed_eligibility: [
            "B.E/B.Tech freshers (CSE,ECE,EEE & IT) with 60% throughout in 10, 12th and Graduation with no active backlog",
            "Year of passing: 2021",
            "Candidates should be open to get posted at any of the above location"
        ],
        professional_experience: null,
        skills: null,
        job_description: null,
        apply_link: "https://jobs.itcinfotech.com/referral/#/job-list",

    },
    {
        id : 6,
        post_date: "August 4, 2021",
        semi_heading: "GlobalEdge(Part of Capgemini) Off Campus Drive 2021 Details",
        heading: "GlobalEdge Off Campus Drive 2021 | B.E/B.Tech | 2019/2020/2021 Batch | Last Date: 12 August 2021",
        description: "GlobalEdge scheduled to hire Software Engineers for B.E/B.Tech 2019/2020/2021 batch graduates. The detailed eligibility and application process are given below.",
        img_url: "https://media-exp1.licdn.com/dms/image/C560BAQH9_lp1TFOd2Q/company-logo_200_200/0/1617875580082?e=2159024400&v=beta&t=qx7v9pAeNFZcTCe8yID0vTrGELMChxGDTpiIfKN-GY0",
        job_role: "Software Engineers",
        qualification:	"B.E/B.Tech",
        batch: "2019/2020/2021",
        experience: "Freshers",
        salary:	"Rs. 3.8 LPA",
        job_location: "Bangalore(Work from home/Office)",
        drive_location: "Will be informed later",
        drive_date: "Will be informed later",
        last_date: "12 August 2021",
        detailed_eligibility: [
            "BE/BTech -2019,2020 and 2021 BATCH",
            "Engineering Branches – ECE, ISE, CSE and ITE",
            "Percentage Cut-off – 10th , 12th and Engineering – 65%",
            "Mandate Certification:Manual/ Automation Testing certification",
            "Service Agreement : Yes, on prorata basis -24 months from the effective date of employment",
            "CTC Offered: INR 12,000/- for first 6 Months and upon employment INR 3.8 LPA"
        ],
        professional_experience: null,
        skills: [
            "Good attitude",
            "Sound knowledge on analytical skills",
            "Good Knowledge on Automation selenium and Networking concepts",
            "Very good communication skills – verbal and written English"
        ],
        job_description: null,
        apply_link: "https://match.myanatomy.in/corporate/customCampaign/view?publicLink=a91f89a4adcabd8bcd96611c5966adcd;dc43f54e0d2dee6d149ee1f0dc4b44c8747d1c538223036859dee9c5a6dbef08e171c5c83a3b983e71f16e515668043833e478842fad12316e855288959d9313da7938146c3be8631bbe5496b1a1f08cd4e86478c1bd6fe352ab290bed8670388cd02c2b1c8a53f6dc2f383a487a9166fe6ccf444c2bb3d1bb0f2ca721168a67d6ba321b8989398f6a877a873bd34c122589643fd49612b59a9d307bb67b23ea0dae9dadd47e125d316a0858edc6647a0d0e90a903485c693776820f86dbbdb5&source=n",

    },
    {
        id : 7,
        post_date: "July 31, 2021",
        semi_heading: "Amdocs Off Campus Drive 2021",
        heading: "Amdocs Off Campus Drive 2021 for Software Engineering Associate | Pune/Gurugram",
        description: "Amdocs scheduled to hire Engineering/MCA  for the role of Software Engineering Associate at Pune/Gurugram. The detailed eligibility and application process are given below.",
        img_url: "https://media-exp1.licdn.com/dms/image/C4E0BAQGgOrmC_q_GfA/company-logo_200_200/0/1625110596221?e=2159024400&v=beta&t=FG-VYaCrg2h-rUdAlSp1ck8T6sJTdiYGHTWFPvorsVc",
        job_role: "Software Engineering Associate",
        qualification:	"B.E/B.Tech/M.E/M.Tech/MCA",
        batch: "2021",
        experience: "Freshers",
        salary:	"Rs 4 LPA",
        job_location: "Pune/Gurugram",
        drive_location: null,
        drive_date: "Informed later(Next Week)",
        last_date: "ASAP",
        detailed_eligibility: [
            "BE/BTech/ME/MTech(CSE/ENTC /IT/ENC ) & MCA 2021 Batch students",
            "Percentage criteria : Throughout 60% (10th,12th,Diploma & UG Aggregate 60%)",
            "No year down.",
            "Passing out Year – 2021",
            "Should not have attended Amdocs Aptitude/Technical test in last 1 year."
        ],
        professional_experience: null,
        skills: null,
        job_description: [
            "design, develop, modify, debug and/or maintain software code according to functional, non-functional and technical design specifications.",
            "follow Amdocs software engineering standards, applicable software development methodology and release processes, to ensure code is maintainable, scalable, and supportable, and demo the software products to stakeholders.",
            "investigate issues by reviewing/debugging code, provide fixes and workarounds, and review changes for operability to maintain existing software solutions.",
            "work within a team, collaborate and add value through participation in peer code reviews, provide comments and suggestions, and work with cross functional teams to achieve goals.",
            "assume technical accountability for your specific work products within an application and provide technical support during solution design for new requirements.",
            "be encouraged to actively look for innovation, continuous improvement, and efficiency in all assigned tasks."
        ],
        apply_link: "https://docs.google.com/forms/d/e/1FAIpQLSdweiY_PkEwxdusrsQuK59emDUh5ejafY9cqvqopOG3TPc8VQ/viewform",

    },
    {
        id : 8,
        post_date: "July 30, 2021",
        semi_heading: "Innovaccer Off Campus Drive 2021",
        heading: "Innovaccer Off Campus Drive 2021 | B.E/B.Tech/M.E/M.Tech | Last Date: 4 August 2021",
        description: "Innovaccer scheduled to hire Associate Software Engineers for B.E/B.Tech/M.Tech graduates at Noida. The detailed eligibility and application process are given below.",
        img_url: "https://www.freshersvoice.com/wp-content/uploads/2021/07/Innovaccer-Off-Campus.jpg",
        job_role: "Data Analyst",
        qualification:	"B.E/B.Tech/M.Tech",
        batch: "2021",
        experience: "Freshers",
        salary:	"Best in Industry",
        job_location: "Noida(Post Pandemic)",
        drive_location: null,
        drive_date: "Will be informed later",
        last_date: "4 August 2021",
        detailed_eligibility: [
            "B.Tech/B.E/ M.Tech (only 2021 batch) with no standing backlog(s)",
            "B.Tech/B.E/ M.Tech (only 2021 batch) in Computer Sciences or related discipline",
            "Should be well versed with SQL, Python and PowerBI",
            "Should have very strong analytical and problem-solving skills.",
            "Should be detail-oriented with strong focus on accuracy.",
            "Ability to understand complex requirements and derive solutions.",
            "Ability to learn quickly and desire to take on new challenges.",
            "Ability to work on multiple assignments and achieve objectives and deadlines.",
            "Quick learner with an interest in big data.",
        ],
        professional_experience: null,
        skills: null,
        job_description: [
            "help us in simplifying the complexities of the U.S Healthcare Data, be it clinical, claim or ADT. You will be a part of the expanding Healthcare Innovations team, with plenty of opportunities to interact with project stakeholders at all levels of the organization. Your primary focus will be to design and develop the interfaces for clinical and claim data to bring the actionable insights on the dashboards. You will be required to analyze the US healthcare measures and Value-Based Care Models to identify trends, scenarios, outcomes and value drivers. This is a fast-paced, collaborative and iterative environment requiring quick learning, agility and flexibility.",
        ],
        apply_link: "https://innovaccer.com/careers/",

    },
    {
        id : 9,
        post_date: "July 28, 2021",
        semi_heading: "IBM Off Campus Drive 2021",
        heading: "IBM Off Campus Drive 2021 | B.E/B.Tech/M.E/M.Tech/MCA | Across India",
        description: "IBM scheduled to hire for the role of Associate Systems Engineer for  B.E/B.Tech/M.E/.Tech/MCA graduates. The detailed eligibility criteria and application process are given below.",
        img_url: "https://www.freshersvoice.com/wp-content/uploads/2017/01/IBM-Off-Campus.png",
        job_role: "Associate Systems Engineer",
        qualification:	"B.E/B.Tech/M.E/M.Tech/MCA",
        batch: "2018/2019/2020/2021",
        experience: "Freshers",
        salary:	"upto Rs 4.2 LPA",
        job_location: "Gurugram/Bangalore/Pune/Chennai/Hyderabad/Kolkata",
        drive_location: null,
        drive_date: null,
        last_date: "ASAP",
        detailed_eligibility: [
            "Degree Courses: Graduation and Post-Graduation – B.E/ B.Tech/ M.E./ M.Tech /M.Sc /MCA – 60% or 6.0 CGPA.(Calculation of qualifying marks=Sum total of marks obtained divided by Sum total of maximum marks obtainable. All subjects will be considered including elective/optional subjects)",
            "Course Completion Year: 2018/ 2019/ 2020/2021 only with less than 2 years experience.",
            "No current backlogs"
        ],
        professional_experience: [
            "Contribution/Leadership: Work on professional projects; work is often reviewed for developmental purposes. Understand the standard mission of the professional group",
            "Impact on Business/Scope: Accountable for individual or team results. You can contribute by supporting activities that are subject to business measurements, impact customer happiness, or impact immediate costs or expenses.",
            "Required Technical and Professional Expertise:",
            "Environment: Professional knowledge related to your KRAs that requires you to demonstrate the ability to absorb professional knowledge quickly and develop skills related to technical, functional, software and soft skills",
            "Communication/Negotiation: Draw upon professional concepts to collaborate with others to carry out assigned duties.",
            "Problem Solving: Recognize job-related problems. Analyze causes using existing techniques or tools, Prepare and recommend solution alternatives."
        ],
        skills: [
            "Defining, analyzing and reviewing technical architecture on required platform and coming up with architecture options and recommendations",
            "Demonstrating strong knowledge of enterprise issues related to IT architecture.",
            "Defining, detailing and scoping the technical requirements into solution architecture and ability to drive an independent project from an architectural stand point.",
            "Will design, develop and/or re-engineer application components, and integrate software packages, programs, and reusable objects residing on multiple platforms.",
            "The Ability to support Technical Consultants and leads in building solutions and providing technical mentoring and guidance."
        ],
        job_description: null,
        apply_link: "https://careers.ibm.com/job/13110119/associate-systems-engineer-bangalore-in/?codes=IBM_CareerWebSite",

    },
    {
        id : 10,
        post_date: "July 23, 2021",
        semi_heading: "Temenos Off Campus Drive 2021",
        heading: "Temenos Off Campus Drive 2021 for Software Engineer | B.E/B.Tech | Rs 6.3 LPA | 5 August 2021",
        description: "Temenos scheduled to hire  B.E/ B.Tech   2020 & 2021 batch graduates for Software Engineer positions. The detailed eligibility and application details are given below.",
        img_url: "https://www.freshersvoice.com/wp-content/uploads/2021/04/Temenos-Off-Campus.jpg",
        job_role: "Software Engineer",
        qualification:	"B.E/B.Tech",
        batch: "2020 & 2021",
        experience: null,
        salary:	"Rs 6.3 LPA",
        job_location: "Chennai/Bangalore/Hyderabad",
        drive_location: null,
        drive_date: "5 August 2021",
        last_date: "31 July 2021",
        detailed_eligibility: [
            "Engineering graduates of 2020 & 2021 from streams CSE,IT,EC,EEE,E&I",
            "CGPA: 8 or 80% above"
        ],
        professional_experience: null,
        skills: null,
        job_description: null,
        apply_link: "https://docs.google.com/forms/d/1skASenaR_VDj53fTq0dUeDivrKECEpx3aRU-fQ3PieE/viewform?edit_requested=true",
    },
    
]